include: 
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: corne_dongle
